export default function TermsPage() {
  return (
    <div style={{ background: "var(--background)" }}>
      <section className="py-16" style={{ background: "var(--surface-warm)" }}>
        <div className="max-w-prose mx-auto px-6">
          <h1 className="font-display font-bold text-4xl mb-2" style={{ color: "var(--text-primary)" }}>Terms of Service</h1>
          <p className="text-sm" style={{ color: "var(--text-muted)" }}>Effective: March 2026</p>
        </div>
      </section>
      <section className="py-16">
        <div className="max-w-prose mx-auto px-6 flex flex-col gap-8 text-base leading-relaxed" style={{ color: "var(--text-secondary)" }}>
          {[
            ["1. Service", "Partypop is an AI-powered party planning tool. We provide plans, checklists, vendor recommendations, and organizational tools for personal use. We do not book vendors on your behalf, guarantee vendor availability, or take responsibility for third-party vendor performance."],
            ["2. Accounts", "You must be 18+ to create an account. You are responsible for maintaining account security. One account per person."],
            ["3. Free Tier", "Free accounts are limited to 1 party plan. This limit may change with notice."],
            ["4. Subscriptions", "Party Pro ($9/month) and Family ($19/month) are billed monthly via Stripe. Cancel anytime in Account Settings. 14-day refund policy for new subscribers."],
            ["5. AI-Generated Content", "Party plans are generated by AI (OpenAI GPT-4o). Plans are suggestions — review all recommendations before acting on them. Partypop does not guarantee AI accuracy."],
            ["6. Vendor Recommendations", "Vendor data is provided for informational purposes. Partypop does not endorse, verify, or guarantee any vendor. Always verify vendor credentials independently before booking."],
            ["7. Acceptable Use", "Do not use Partypop to plan events that violate applicable laws. Do not attempt to scrape, reverse-engineer, or abuse the platform."],
            ["8. Limitation of Liability", "Partypop is not liable for party outcomes, vendor failures, or decisions made based on AI-generated content."],
            ["9. Changes", "We may update these terms with 30 days notice via email."],
          ].map(([title, body]) => (
            <div key={title as string}>
              <h2 className="font-display font-bold text-xl mb-3" style={{ color: "var(--text-primary)" }}>{title}</h2>
              <p>{body}</p>
            </div>
          ))}
          <p style={{ color: "var(--text-muted)" }}>Contact: hello@partypopai.com</p>
        </div>
      </section>
    </div>
  );
}
